#!/bin/bash

set -uo pipefail

umask 077
TTY="/dev/$(ps -p $$ -o tty=)"

################################################################
# Helper functions

function die() { echo "[1;31merror:[m $*" >&2; exit 1; }
function status() { echo "${had_status+$'\n'}[1;33m$*[m"; had_status=1; }
function flush_stdin() { while read -r -t 0.01 empty_stdin < "$TTY"; do true; done; }
function ask() {
	local response
	while true; do
		flush_stdin
		read -r -p "$* (Y/n) " response < "$TTY" || die "Error in read"
		case "${response,,}" in
			'') return 0 ;;
			y|yes) return 0 ;;
			n|no) return 1 ;;
			*) continue ;;
		esac
	done
}
# $1 = src, $2 = dest, $3 = owner, $4 = mode
function install_file() {
	cp    "$1" "$2" || die "Could not copy '$1' to '$2'"
	chown "$3" "$2" || die "Could not chown '$2'"
	chmod "$4" "$2" || die "Could not chmod '$2'"
}

# $1: Variable to store result array into
# $2: Prompt (string)
function ask_array() {
	# Indirectly reference result array
	declare -n ref=$1
	ref=()

	# Prompt the user for their choice(s)
	flush_stdin
	read -r -p "$2" ref < $TTY || die "Error in read"

	# Check if input is empty (user selected none)
	if [ -z "$ref" ]; then
		ask_array $1 $2
	fi
}

# $1: Directory FROM
# $2: Directory TO (NO END SLASH)
function install_folder() {
	mkdir -p -m700 "$2" || die "Could not create directory '$d'"
	for d in $(find "$1" -type d -printf '%P\n'); do
		mkdir -p -m700 "$2/$d" || die "Could not create directory '$d'"
		chown minecraft: "$2/$d" || die "Could not chown directory '$d'"
	done

	for f in $(find "$1" -type f -printf '%P\n'); do
		install_file "$1/$f" "$2/$f" minecraft: 600
	done
}

################################################################
# Ensure that all required tools are installed

abort=0
for i in jq git tmux rdiff-backup java openssl; do
	if ! type "$i" &>/dev/null; then
		echo "[1;31mmissing: [1;33m$i[m" >&2
		abort=1
	fi
done

[[ "$abort" == "0" ]] \
	|| die "Please install the missing tools first."


################################################################
# Ensure memory requirements are met and we have root access

total_ram_gibi=$(free -g | grep -oP '\d+' | head -n1)
if [[ $total_ram_gibi -le 4 ]]; then
	echo "[31mYour system has [33m${total_ram_gibi}GiB[31m of RAM, which probably is not enough to run minecraft"
	echo "without issues. The recommended minimum amount is _at least_ [33m12GiB[31m.[m"
	ask "Continue anyway?" || die "Installation aborted."
	echo
elif [[ $total_ram_gibi -lt 12 ]]; then
	echo "[31mYour system has [33m${total_ram_gibi}GiB[31m of RAM, which less than the recommended amount of"
	echo "_at least_ [33m12GiB[31m. This will hurt the server performance significantly.[m"
	ask "Continue anyway?" || die "Installation aborted."
	echo
fi

[[ $EUID == 0 ]] || die "Must be root for system-wide installation."


################################################################
# Ensure EULA is accepted

status "Agree to Mojang EULA"
echo "You have to agree to Mojang's EULA to use the server software."
echo "It is available here: https://account.mojang.com/documents/minecraft_eula"
ask "Do you agree to the EULA?" \
	|| die "Installation aborted. EULA must be accepted to continue."


################################################################
# Create minecraft user if necessary

if ! getent passwd minecraft &>/dev/null; then
	status "Creating minecraft user"
	useradd --system --home-dir /var/lib/minecraft --no-create-home minecraft \
		|| die "Could not create user 'minecraft'"
fi

mkdir -p /var/lib/minecraft
chmod 700 /var/lib/minecraft
chown minecraft: /var/lib/minecraft


################################################################
# Setup repository

if [[ -e /var/lib/minecraft/deploy ]]; then
	echo "[33mThe deploy directory /var/lib/minecraft/deploy already exists."
	echo "You can still run the installer again, but it may overwrite some"
	echo "configuration files if you edited them in the meantime.[m"
	ask "Are you sure you want to continue?" \
		|| die "Installation aborted."
fi

cd /var/lib/minecraft \
	|| die "Could not change into /var/lib/minecraft"

if [[ -e deploy ]]; then
	status "Updating deploy repository"
	runuser -u minecraft -- git -C deploy pull \
		|| die "Could not pull repository"
else
	status "Cloning deploy repository"
	runuser -u minecraft -- git clone "https://github.com/Dan-megabyte/minecraft-server-bootstrap" deploy \
		|| die "Could not clone repository"
fi

cd deploy \
	|| die "Could not change into deploy directory"

################################################################
# Setup Velocity Proxy Server
status "Setting up velocity proxy server"

# generate and deploy velocity secret
VELOCITYSECRET=$(openssl rand -base64 16) \
	|| die "Could not generate velocity secret"
install_file <(echo -n "$VELOCITYSECRET") proxy/forwarding.secret minecraft: 600

# deploy default velocity config
install_folder "contrib/default_config/proxy" "proxy"

################################################################
# Setup backend Minecraft Servers

status "Setting up backend minecraft servers"

server_names=()
ask_array server_names "What are the names of the backend servers that you want to install?: "

delete_default="false"
if ask 'Afterwards, do you want to delete the default server template named "default"?'; then
	delete_default="true"
elif ask 'Would you like to configure it too then?'; then
	server_names+="default"
fi

for server_name in $server_names; do
	if [ "$server_name" != "default" ]; then
		echo "Copying default server template"
		install_folder "servers/default" "servers/$server_name"
	fi

	status "Configuring $server_name server"
	install_file <(echo "eula=true") "servers/$server_name"/eula.txt minecraft: 600

	install_folder "contrib/default_config/server" "servers/$server_name"

	sed -i 's|{{VELOCITYSECRET}}|'"$VELOCITYSECRET"'|' "servers/$server_name"/config/paper-global.yml \
		|| die "Could not insert velocity secret in paper-global.yml"

	echo "Depending on your player base, you might want to allow certain gamplay"
	echo "exploits on your server. These are fixed by default in PaperMC, but would"
	echo "allow your players to build certain vanilla machines (TNT blast chambers,"
	echo "bedrock removal, ...). My personal recommendation is to answer with yes"
	echo "to all of these questions."
	echo

	if ask "Allow headless pistons and bedrock breaking?"; then
		sed -i 's|allow-headless-pistons: false|allow-headless-pistons: true|' "servers/$server_name"/config/paper-global.yml \
			|| die "Could not replace allow-headless-pistons config"
		sed -i 's|allow-permanent-block-break-exploits: false|allow-permanent-block-break-exploits: true|' "servers/$server_name"/config/paper-global.yml \
			|| die "Could not replace allow-permanent-block-break-exploits config"
	fi

	if ask "Allow piston TNT duping?"; then
		sed -i 's|allow-piston-duplication: false|allow-piston-duplication: true|' "servers/$server_name"/config/paper-global.yml \
			|| die "Could not replace allow-piston-duplication config"
	fi

	if ask "Enable Anti-XRAY?"; then
		sed -i 's|false # ANTI_XRAY|true|' "servers/$server_name"/config/paper-world-defaults.yml \
			|| die "Could not replace ANTI_XRAY config"
	else
		sed -i 's|false # ANTI_XRAY|false|' "servers/$server_name"/config/paper-world-defaults.yml \
			|| die "Could not replace ANTI_XRAY config"
	fi

	if ask "Replenish loot in loot chests after 1-2 realtime days?"; then
		sed -i 's|auto-replenish: false|auto-replenish: true|' "servers/$server_name"/config/paper-world-defaults.yml \
			|| die "Could not replace auto-replenish config"
	fi

	if ask "Disable hopper item move event to reduce lag?"; then
		sed -i 's|disable-move-event: false|disable-move-event: true|' "servers/$server_name"/config/paper-world-defaults.yml \
			|| die "Could not replace disable-move-event config"
	fi

	if ask "Increase view-distance to 15 chunks?"; then
		sed -i 's|view-distance=10|view-distance=15|' "servers/$server_name"/server.properties \
			|| die "Could not replace view-distance config"
	fi
done

if [ "$delete_default" == "true" ]; then
	status 'deleting "default" template server'
	rm -r "servers/default"
fi

if ask "Download all initial server files through update.sh?"; then
	runuser -u minecraft -- ./update.sh < "$TTY" \
		|| echo "Could not update server files, continuing later"
fi


################################################################
# Install systemd services

status "Installing service files"
./contrib/install.sh < "$TTY" \
	|| die "Error while installing service files"


################################################################
# Enable and start services

status "Starting services ..."
echo "[33mSystem services for the proxy and server will now be enabled and started."
echo "If you want to adjust any proxy related configuration, you may want to start"
echo "them manually later.[m"
echo

services=" minecraft-proxy"
for server_name in $server_names; do
	services+=" minecraft-server@$server_name"
done

postponed_service_message=""
if ask "Enable and start system services now?"; then
	systemctl enable --now minecraft-server minecraft-proxy < "$TTY" \
		|| die "Error while enabling services"
else
	postponed_service_message="
You have postponed enabling the system services. Make sure to execute the
following command when you are ready to start the server:

[1;32m    systemctl enable --now $services[m
"
fi


################################################################
# Success message

cat <<EOF
[1m================================================================================[m
                            [1;32mInstallation successful![m
[1m================================================================================[m
The server and proxy have been installed successfully! The PaperMC minecraft
server will be started when a player connects via the proxy. Be aware that the
first start may take a while due to world generation.

Please make sure that TCP port [35m25565[m (server), [35m25566[m (multiplex 1) and [35m8100[m
(bluemap webserver) are exposed to the internet via a port-foward or similar
mechanism. If you want to change your server configuration, please do so now.
$postponed_service_message
For more information, visit [35mhttps://github.com/oddlama/minecraft-server[m
[1m================================================================================[m
EOF
